return PlaceObj('ModDef', {
	'title', "Enemy Avoid Militia",
	'description', "[h1]Enemy Avoid Militia[/h1]\n\nAre you tired of Diamond Shipments driving through your elite mercenary squads like they're on a Sunday stroll? Do Legion attack squads treat your heavily fortified militia outposts as a minor traffic inconvenience?\n \n\n[b]Enemy Avoid Militia[/b] re-educates the AI to respect your personal space. By overhauling the satellite pathfinding logic, this mod forces enemy squads to perceive your presence — mercs and militia alike — as a massive strategic deterrent.\n \n\n[h2]Features[/h2]\n \n\n[b]- Tactical Deterrence[/b]\nEnemies now calculate routes around sectors where your mercenaries or militia are stationed, unless that sector is their intended target. No more casual strolls through your lines.\n \n\n[b]- Smart Diamond Shipments[/b]\nDynamic diamond shipments will no longer commit suicide by walking into your militia. They will actively seek the path of least resistance — forcing you to stay mobile and cut them off yourself.\n \n\n[b]- Optimized Performance[/b]\nFeatures a custom-coded, high-speed pathfinding engine to ensure diamond shipments can calculate new routes every time they are spawned, to adjust to the current situation on the map without slowing down the game.\n\n(In vanilla they are just using routes that are precalculated at the start of the game and never updated to the situation, which is why they always run into the same cities)\n \n\n[b]- Player-Friendly[/b]\nThese changes only affect enemy factions (The Legion and Diamond Shipments). Your own mercs have completely unchanged pathfinding.\n \n \n[i]Stop being a speed bump. Become a wall.[/i]",
	'image', "Mod/igkEv74/Images/thumbnail.jpg",
	'last_changes', "Fix issue with game LUA complaining about global variable setting",
	'id', "igkEv74",
	'author', "KeldorKatarn",
	'version_major', 1,
	'version_minor', 1,
	'version', 14,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Script.lua",
	},
	'default_options', {},
	'saved', 1775705569,
	'code_hash', 3162334776493593564,
	'screenshot1', "Mod/igkEv74/Images/screenshot1.jpg",
	'screenshot2', "Mod/igkEv74/Images/screenshot2.jpg",
	'screenshot3', "Mod/igkEv74/Images/screenshot3.jpg",
	'affected_resources', {},
	'steam_id', "3699261761",
	'TagCombat&AI', true,
	'TagEnemies', true,
	'TagSatview&Operations', true,
})